package org.example.creditrisk;

import java.util.List;

public record CustomerRiskSummaryResponse(
        String customerKey,
        String customerName,
        String customerCategory,
        String phoneNumber,
        boolean manualHold,
        String manualHoldReason,
        Integer paymentTermsDays,
        int customerTenureDays,
        double lifetimeSales,
        double salesLast30Days,
        double salesLast90Days,
        double salesLast180Days,
        double salesLast365Days,
        int totalOrders,
        int ordersLast30Days,
        int ordersLast90Days,
        double averageOrderValue,
        double averageOrderValueLast90Days,
        Double creditLimit,
        String creditLimitSource,
        double currentOutstanding,
        double overdueAmount,
        int overdueInvoiceCount,
        int maximumOverdueDays,
        Double creditUtilization,
        int totalInvoices,
        int paidInvoices,
        int unpaidInvoices,
        double onTimePaymentPercentage,
        double averagePaymentDelayDays,
        double maximumPaymentDelayDays,
        int paymentFailuresLast90Days,
        int brokenPaymentPromises,
        int openPaymentPromiseCount,
        double openPaymentPromiseAmount,
        String nextPaymentDate,
        String lastPaymentDate,
        double lastPaymentAmount,
        String lastOrderDate,
        double lastOrderAmount,
        double paymentScore,
        double businessScore,
        double riskScore,
        String riskCategory,
        String paymentBehaviour,
        String businessValue,
        Double recommendedCreditLimit,
        List<ScoreComponent> paymentComponents,
        List<ScoreComponent> businessComponents,
        List<String> dataQualityWarnings,
        List<String> alerts
) {
    public static CustomerRiskSummaryResponse from(
            CustomerRiskMetrics m,
            CustomerRiskScore score,
            Double recommended
    ) {
        return new CustomerRiskSummaryResponse(
                m.getCustomerKey(),
                m.getCustomerName(),
                m.getCustomerCategory(),
                m.getPhoneNumber(),
                m.isManualHold(),
                m.getManualHoldReason(),
                m.getPaymentTermsDays(),
                m.getCustomerTenureDays(),
                m.getLifetimeSales(),
                m.getSalesLast30Days(),
                m.getSalesLast90Days(),
                m.getSalesLast180Days(),
                m.getSalesLast365Days(),
                m.getTotalOrders(),
                m.getOrdersLast30Days(),
                m.getOrdersLast90Days(),
                m.getAverageOrderValue(),
                m.getAverageOrderValueLast90Days(),
                m.getEffectiveCreditLimit(),
                m.getCreditLimitSource(),
                m.getCurrentOutstanding(),
                m.getOverdueAmount(),
                m.getOverdueInvoiceCount(),
                m.getMaximumOverdueDays(),
                m.getCreditUtilization(),
                m.getTotalInvoices(),
                m.getPaidInvoices(),
                m.getUnpaidInvoices(),
                m.getOnTimePaymentPercentage(),
                m.getAveragePaymentDelayDays(),
                m.getMaximumPaymentDelayDays(),
                m.getPaymentFailuresLast90Days(),
                m.getBrokenPaymentPromises(),
                m.getOpenPaymentPromiseCount(),
                m.getOpenPaymentPromiseAmount(),
                m.getNextPaymentDate(),
                m.getLastPaymentDate(),
                m.getLastPaymentAmount(),
                m.getLastOrderDate(),
                m.getLastOrderAmount(),
                score.paymentScore(),
                score.businessScore(),
                score.riskScore(),
                score.riskCategory(),
                score.paymentBehaviour(),
                score.businessValue(),
                recommended,
                score.paymentComponents(),
                score.businessComponents(),
                m.getDataQualityWarnings(),
                m.getAlerts()
        );
    }
}
